# SPDX-License-Identifier: Apache-2.0
import os

Import('*')

lab = os.environ['OPENURMA_LAB_ROOT']
env.Append(CPPPATH=[lab, os.path.join(lab, 'sources/simbricks/lib')])

SimObject('UbHostAdapter.py', sim_objects=['UbHostAdapter'])
Source('UbHostAdapter.cc')
Source(os.path.join(lab, 'components/udma-device-sim/simbricks_base_portable.c'))
