// SPDX-License-Identifier: Apache-2.0
#pragma once

#include <cstdint>

namespace ubsim::proto::net {

inline constexpr std::uint32_t kUdmaWireMagic = 0x31574455U; // "UDW1"
inline constexpr std::uint8_t kUdmaWireVersion = 3;
inline constexpr std::uint16_t kUdmaWireFragmented = 1U << 0;
inline constexpr std::uint16_t kUdmaWireLastFragment = 1U << 1;
inline constexpr std::uint16_t kUdmaWireCtpSegment = 1U << 2;
// A request without kUdmaWireCtpSegment is a complete WQE submission.  It may
// be split into IPC chunks using Fragmented/LastFragment, but those chunks are
// not transport packets.  A message with kUdmaWireCtpSegment is an individual
// target-DMA request or completion generated by the native CTP engine.

enum class UdmaOperation : std::uint8_t {
    Send = 0,
    SendImmediate = 1,
    Write = 3,
    ReadRequest = 6,
    WriteAck = 0x83,
    ReadResponse = 0x85,
};

struct [[gnu::packed]] UdmaWireHeader {
    std::uint32_t magic;
    std::uint8_t version;
    std::uint8_t operation;
    std::uint16_t flags;
    std::uint32_t source_jetty;
    std::uint32_t destination_jetty;
    std::uint32_t tpn;
    std::uint32_t segment;
    std::uint64_t remote_address;
    std::uint64_t immediate;
    std::uint64_t request_id;
    std::uint32_t ta_ssn;
    std::uint32_t transfer_length;
    std::uint32_t payload_length;
    std::uint32_t payload_offset;
};
static_assert(sizeof(UdmaWireHeader) == 64);

} // namespace ubsim::proto::net
